### ISSUE TITLE
Streams getting terminated after 1 minute

### ISSUE THREAD

**Issue by Phineas** [mustafaturan/sse#9]
Getting a pretty weird issue, tried to debug it and from what I can see it looks like the SSE.Server process is being killed somehow, looking at the observer. This always happens after 1 minute exactly of the request being open.

Here's an example of what happens on the Chrome "Timing" tab for the request:
![issue](https://i.imgur.com/FQPqI6Z.png)
And then in the JS console, I see `GET http://localhost:8080/pipe net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)` - same happens in Safari.

I'm using a KA value of 1000ms.

I also don't see the "SSE connection (#{inspect(pid)}) closed!" message whenever I close the eventsource, if that's any help to you.

Thanks!

**Comment by mustafaturan** [comment]
You need to `:idle_timeout` option to cowboy if you are using cowboy version >= 2.5.0

**Comment by mustafaturan** [comment]
https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/
